### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no attach in java.library.path

### ISSUE THREAD

**Issue by hongbing** [arturmkrtchyan/sizeof4j#1]
Hi,
When I run the "main" method,it throw the Exception like this:

> Exception in thread "main" java.lang.UnsatisfiedLinkError: no attach in java.library.path
>     at java.lang.ClassLoader.loadLibrary(Unknown Source)
>     at java.lang.Runtime.loadLibrary0(Unknown Source)
>     at java.lang.System.loadLibrary(Unknown Source)
>     at sun.tools.attach.LinuxVirtualMachine.<clinit>(LinuxVirtualMachine.java:336)
>     at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
>     at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:213)
>     at com.arturmkrtchyan.sizeof4j.calculation.hotspot.HotSpotHistogram.heapHistogram(HotSpotHistogram.java:28)
>     at com.arturmkrtchyan.sizeof4j.calculation.hotspot.HistogramCalculationStrategy.calculateShallow(HistogramCalculationStrategy.java:15)
>     at com.arturmkrtchyan.sizeof4j.SizeOf.shallowSize(SizeOf.java:63)
>     at com.arturmkrtchyan.sizeof4j.Main.main(Main.java:31)

I debug it ,I find the place where it throw the exception:

> vm = VirtualMachine.attach(processId);

My  **java.library.path** is **usr/local/lib**,And  I already add it in the **Java build path->Libraries->Native Library location**.

I don't know what the missing shared library is, the exception doesn't show me.

I hope you can help me ?
Thx.

**Comment by arturmkrtchyan** [comment]
Hi @hongbing which version of java are you using ?  Are you running using it as mvn project ? Basically java's tools.jar is missing. Check out pom.xml

**Comment by hongbing** [comment]
Hi，I use it as a maven project. And I include the tools.jar in pom.xml like this:

```
    <profile>
        <id>default-tools.jar</id>
        <activation>
            <property>
                <name>java.vendor</name>
                <value>Oracle Corporation</value>
            </property>
        </activation>
        <dependencies>
            <dependency>
                <groupId>com.sun</groupId>
                <artifactId>tools</artifactId>
                <version>1.7</version>
                <scope>system</scope>
                <systemPath>${JAVA_HOME}/lib/tools.jar</systemPath>
            </dependency>
        </dependencies>
    </profile>

    <profile>
        <id>release</id>
        <properties>
            <skipSigning>false</skipSigning>
        </properties>
    </profile>

    <profile>
        <id>develop</id>
        <activation>
            <activeByDefault>true</activeByDefault>
        </activation>
    </profile>
```

The other related settings are:
java version:

> hongbing@Lenovo:~$ java -version
> java version "1.7.0_21"
> Java(TM) SE Runtime Environment (build 1.7.0_21-b11)
> Java HotSpot(TM) 64-Bit Server VM (build 23.21-b01, mixed mode)

and The $JAVA_HOME is:

> /usr/java/jdk1.7.0_21

The java envirement setting is in **/etc/profile**:

> #set java environment
> export JAVA_HOME=/usr/java/jdk1.7.0_21
> export JRE_HOME=${JAVA_HOME}/jre
> export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
> export PATH=$PATH:$JAVA_HOME/bin
> export JAVA_HOME CLASSPATH PATH

I add **System.out.println(System.getProperty("java.library.path"));** in main class,it print 

> /usr/local/lib

but still throw the same exception. what should I do now?

**Comment by arturmkrtchyan** [comment]
Does your library path contain libattach.so file ? If no can you check if
you have it at all ? If its in different location you can set additional
library path via LD_LIBRARY_PATH env variable  and check again.

**Comment by hongbing** [comment]
It just miss the **libattach.so** .
And I copy it into **/usr/local/lib**,it works.
Thanks a lot.

**Comment by arturmkrtchyan** [comment]
Great! I'm closing the ticket now.
